### ISSUE TITLE
 Doc's <ComponentPreview/>  tab switch cause sidebar reflow

### ISSUE THREAD

**Issue by Lorde4Avalon** [jolbol1/shadcn-aria#10]
Just encountered this impressive UI lib！
However, I noticed that the <ComponentPreview/> comp at the bottom of the doc page cause left&right sidebar to reflow during tab switch, which seem like a bad UX in my opinion.
![20240112161758_rec_](https://github.com/jolbol1/shadcn-aria/assets/74342663/6465aa29-bf18-4e17-b55a-545f6995701c)
Wanna know your opinion

**Comment by jolbol1** [comment]
Hey @Lorde4Avalon cheers for the report. Thats an odd issue that definitely shouldn't be happening. Will take a look thanks!
