### ISSUE TITLE
Comparing shadcn-aria and Draft UI

### ISSUE THREAD

**Issue by corydeppen** [jolbol1/shadcn-aria#5]
Great work on getting this library started. I was wondering if you've considered collaborating with the folks working on the [Draft UI](https://draft-ui.com/) project, which appears to share some of the goals as shadcn-aria. If the two are as closely aligned as they seem, it might be a great opportunity to focus efforts on a single project.

cc @IHIutch

**Comment by jolbol1** [comment]
Yeah I've seen this library. I'd make a PR if I find an area I can help in. If im honest Id prefer DraftUI as its not closely tied like mine to another persons name/library. Would be cool to add themes to I guess?

**Comment by IHIutch** [comment]
Hey! I'd absolutely be open to collaborating. One note I'd like to make is that I've intentionally avoided following some of the decisions of shadcn/ui. While I think that library is excellent, my goal with Draft UI is to show off React Aria Components as much as possible and focus on accessibility. 

Theming is an interesting idea (albeit something I've also stayed away from) but I think [Park UI](https://park-ui.com/) have done something very clever with their approach. 

One thing shadcn/ui has done well that I'd like to emulate is showing more complete examples of a UI system coming together. I think that would be a cool place to focus not only on the accessibility and composability of React Aria but also on accessibility between the various pieces (eg. usage of landmarks, keyboard navigation, etc.) As an example, I read an [article about the poor experience of "seat picker" interfaces](https://www.tpgi.com/accessibility-theater/) recently. IMO, this would be a cool way to demonstrate the use of React Aria and create an example of a typically challenging interface. Obviously, there are plenty of other directions, but this felt like a place that could differentiate React Aria/Draft UI from just being a "UI Library"
