### ISSUE TITLE
Use Sly CLI for automatic installation?

### ISSUE THREAD

**Issue by kentcdodds** [jolbol1/shadcn-aria#9]
Cool that you're working on this! Good call on the name change as well 👍

I noticed you have manual installation. DraftUI opted to use https://sly-cli.fly.dev/ to support automatic installation of components and I think you may find that useful as well.

**Comment by jolbol1** [comment]
Hey @kentcdodds, good suggestions I've been meaning to do just that!

Funnily enough Im the one who added DraftUI to sly via PR, just need to get mine done. Will work on soon.

**Comment by kentcdodds** [comment]
Oh nice! I'm curious whether there's any interest in DraftUI and JollyUI joining forces. Could be nice to have just a single project trying to solve this problem.

**Comment by jolbol1** [comment]
> Oh nice! I'm curious whether there's any interest in DraftUI and JollyUI joining forces. Could be nice to have just a single project trying to solve this problem.

We have discussed this before. I think we have slightly different goals at the moment as my library is built with the shadcn styles whereas draftUI does not have styling yet as it uses hardcoded tailwind colors.

At the moment I think we are just helping eachother out where we can, Might be a chance in the future!
